name: 'Generate kicad files'
description: 'Generate kicad files like a pdf schematic, bom files, etc.'
branding:
  icon: 'cpu'
  color: 'yellow'

inputs:
  file:
    description: 'The location to the schematic or PCB file.'
    required: true
  type:
    description: >
      Export type, choose one of the following:
      - schematic_pdf
      - schematic_svg
      - schematic_bom
      - schematic_netlist
      - pcb_step
      - pcb_pos
      - pcb_gerbers
      - pcb_drill
      - pcb_gerbers_drill
    required: true
  layers:
    description: >
      The layers that need to be exported in a comma seperated list. Example: "F.Cu,B.cu".
      The layers can be set by the following types:
      - pcb_gerbers
      - pcb_gerbers_drill

# outputs:
#   output-type:
#     description: >
#       The output type of the files, this can be the following type:
#       - file
#       - folder
#     value: XXXX
#   output-location:
#     description: 'The location of the output files.'
#     value: ${{ github.action_path }}/output

runs:
  using: "composite"
  steps:
    - id: export-files
      name: 'Export files.'
      run: ${{ github.action_path }}/export_files.sh "${{ inputs.file }}" "${{ inputs.type }}" "${{ inputs.layers }}"
      shell: bash