name: "Generate KiCad files"
description: "Generate KiCad files like a pdf schematic, bom files, etc."
branding:
  icon: "cpu"
  color: "yellow"

inputs:
  file:
    description: "The location to the schematic or PCB file."
    required: true
  type:
    description: >
      Export type, choose one of the following:
      - schematic_pdf
      - schematic_svg
      - schematic_bom
      - schematic_netlist
      - pcb_step
      - pcb_pos
      - pcb_gerbers
      - pcb_drill
      - pcb_gerbers_drill
    required: true
  layers:
    description: >
      The layers that need to be exported in a comma separated list. Example: "F.Cu,B.cu". If no layers are given, all layers are exported.
      The layers can be set by the following types:
      - pcb_gerbers
      - pcb_gerbers_drill
  black-and-white:
    description: >
      Export footprints in black and white.
      The black-and-white option be used by the following types:
      - schematic_pdf
      - schematic_svg
    default: false

runs:
  using: "composite"
  steps:
    - id: export-files
      name: "Export files."
      run: ${{ github.action_path }}/export_files.sh --type "${{ inputs.type }}" --layers "${{ inputs.layers }}" --black-and-white "${{ inputs.black-and-white }}" "${{ inputs.file }}"
      shell: bash
