name: 'Generate kicad files'
description: 'Generate kicad files like a pdf schematic, bom files, etc.'
branding:
  icon: 'cpu'
  color: 'yellow'

inputs:
  file:
    description: 'The location to the schematic or PCB file.'
    required: true
  type:
    description: >
      Export type, choose one of the following:
      - schematic_pdf
      - schematic_svg
      - schematic_bom
      - schematic_netlist
      - pcb_step
      - pcb_pos
      - pcb_gerbers
      - pcb_drill
      - pcb_gerbers_drill
    required: true
  layers:
    description: >
      The layers that need to be exported in a comma seperated list. Example: "F.Cu,B.cu".
      The layers can be set by the following types:
      - pcb_gerbers
      - pcb_gerbers_drill

runs:
  using: "docker"
  image: ghcr.io/kicad/kicad:8.0
  post-entrypoint: ${{ github.action_path }}/export_files.sh "${{ inputs.file }}" "${{ inputs.type }}" "${{ inputs.layers }}"