name: "Generate KiCad files"
description: "Generate KiCad files like a PDF schematic, BOM files, etc."
branding:
  icon: "cpu"
  color: "yellow"

inputs:
  file:
    description: "The location to the schematic or PCB file."
    required: true
  type:
    description: >
      Export type, choose one of the following:
      - schematic_pdf
      - schematic_svg
      - schematic_bom
      - schematic_netlist
      - pcb_step
      - pcb_pos
      - pcb_gerbers
      - pcb_drill
      - pcb_gerbers_drill
    required: true
  layers:
    description: >
      The layers that need to be exported in a comma-separated list. Example: "F.Cu,B.Cu". If no layers are given, all layers are exported.
      This input can be used when exporting the following types:
      - pcb_gerbers
      - pcb_gerbers_drill
  black-and-white:
    description: >
      Export schematic in black and white.
      This option can be used when exporting the following types:
      - schematic_pdf
      - schematic_svg
    default: false

runs:
  using: "composite"
  steps:
    # STEP 1: Pull the Docker Image
    - name: Pre-pull Docker Image
      run: docker pull docker.io/kicad/kicad:8.0
      shell: bash

    # STEP 2: Run Docker Command for Export
    - id: export-files
      name: Export KiCad Files Using Docker
      run: |
        mkdir -p generated-files
        docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -w "/workspace" \
          docker.io/kicad/kicad:8.0 \
          /bin/bash -c "
            export FILE=${{ inputs.file }}
            export TYPE=${{ inputs.type }}
            export LAYERS=${{ inputs.layers }}
            export BLACK_AND_WHITE=${{ inputs.black-and-white }}
            
            OUTPUT_DIR=\"/workspace/generated-files\"

            case \"$TYPE\" in
              schematic_pdf)
                kicad-cli sch export pdf --black-and-white=$BLACK_AND_WHITE \"$FILE\" -o \"$OUTPUT_DIR/schematic.pdf\"
                ;;
              schematic_svg)
                kicad-cli sch export svg --black-and-white=$BLACK_AND_WHITE \"$FILE\" -o \"$OUTPUT_DIR/schematic.svg\"
                ;;
              schematic_bom)
                kicad-cli sch export bom \"$FILE\" -o \"$OUTPUT_DIR/bom.csv\"
                ;;
              schematic_netlist)
                kicad-cli sch export netlist \"$FILE\" -o \"$OUTPUT_DIR/netlist.net\"
                ;;
              pcb_step)
                kicad-cli pcb export step \"$FILE\" -o \"$OUTPUT_DIR/board.step\"
                ;;
              pcb_pos)
                kicad-cli pcb export pos \"$FILE\" -o \"$OUTPUT_DIR/pos.csv\"
                ;;
              pcb_gerbers)
                kicad-cli pcb export gerbers --layers=\"$LAYERS\" \"$FILE\" -o \"$OUTPUT_DIR/gerbers\"
                ;;
              pcb_drill)
                kicad-cli pcb export drill \"$FILE\" -o \"$OUTPUT_DIR/drill.drl\"
                ;;
              pcb_gerbers_drill)
                kicad-cli pcb export gerbers-drill --layers=\"$LAYERS\" \"$FILE\" -o \"$OUTPUT_DIR/gerbers-drill\"
                ;;
              *)
                echo \"Invalid type specified\"
                exit 1
                ;;
            esac
          "
      shell: bash

    # STEP 3: Upload Generated Files
    - name: Upload Exported Files
      uses: actions/upload-artifact@v4
      with:
        name: "KiCad Generated Files"
        path: "generated-files"
