name: 'Generate kicad files'
description: 'Generate kicad files like a pdf schematic, bom files, etc.'
branding:
  icon: 'cpu'
  color: 'yellow'

inputs:
  file:
    description: 'The location to the schematic or PCB file.'
    required: true
  type:
    description: >
      Export type, choose one of the following:
      - schematic_pdf
      - schematic_svg
      - pcb_step
      - pcb_gerbers_drill
    required: true

outputs:
  file-location:
    description: 'The location of the output file.'
    value: ${{ steps.export-files.outputs.location }}

runs:
  using: "composite"
  steps:
    - id: export-files
      name: 'Export files.'
      run: echo "location=$(${{ github.action_path }}/export_files.sh "${{ inputs.file }}" "${{ inputs.type }}")" >> $GITHUB_OUTPUT
      shell: bash