name: Add main version tag

on:
  release:
    types: [published]

jobs:
  add-main-version-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract main version number
        id: extract_version
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          MAIN_VERSION=$(echo $TAG_NAME | grep -oP 'v\K[0-9]+')
          echo "::set-output name=main_version::v$MAIN_VERSION"
      - name: Create main version tag
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ steps.extract_version.outputs.main_version }}
          git push origin ${{ steps.extract_version.outputs.main_version }}
