name: tests

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - '*.md'

jobs:
  check-export:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kicad-version: ['7.0']
        type: ['schematic_pdf', 'schematic_svg', 'schematic_bom', 'pcb_step', 'pcb_pos']
        include:
          - type: schematic_pdf
            file: kicad-project.kicad_sch
          - type: schematic_svg
            file: kicad-project.kicad_sch
          - type: schematic_bom
            file: kicad-project.kicad_sch
          - type: pcb_step
            file: kicad-project.kicad_pcb
          - type: pcb_pos
            file: kicad-project.kicad_pcb
    steps:
      - uses: actions/checkout@v3
      - uses: actions-for-kicad/setup-kicad@main
        with:
          version: ${{ matrix.kicad-version }}
      - name: Exoprt file
        uses: ./
        with:
          file: 'tests/kicad-project/${{ matrix.file }}'
          type: ${{ matrix.type }}
      - name: Verifiy output
        run: tests/check-output.sh "${{ matrix.type }}" "${{ matrix.file }}"
        shell: bash