name: tests

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "*.md"

jobs:
  check-export:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kicad-version: ["7.0", "8.0"]
        type:
          [
            "schematic_pdf_color",
            "schematic_pdf_black_white",
            "schematic_svg",
            "schematic_bom",
            "schematic_netlist",
            "pcb_step",
            "pcb_pos",
            "pcb_gerbers",
            "pcb_drill",
            "pcb_gerbers_drill",
          ]
        include:
          - type: schematic_pdf_color
            file: kicad-project.kicad_sch
          - type: schematic_pdf_black_white
            file: kicad-project.kicad_sch
            black-and-white: true
          - type: schematic_svg
            file: kicad-project.kicad_sch
          - type: schematic_bom
            file: kicad-project.kicad_sch
          - type: schematic_netlist
            file: kicad-project.kicad_sch
          - type: pcb_step
            file: kicad-project.kicad_pcb
          - type: pcb_pos
            file: kicad-project.kicad_pcb
          - type: pcb_gerbers
            file: kicad-project.kicad_pcb
          - type: pcb_drill
            file: kicad-project.kicad_pcb
          - type: pcb_gerbers_drill
            file: kicad-project.kicad_pcb
    steps:
      - uses: actions/checkout@v3
      - uses: actions-for-kicad/setup-kicad@main
        with:
          version: ${{ matrix.kicad-version }}
      - name: Export file
        uses: ./
        with:
          file: "tests/kicad-project/${{ matrix.file }}"
          type: ${{ matrix.type }}
      - name: Verifiy output
        run: tests/check-output.sh "${{ matrix.type }}" "${{ matrix.file }}"
        shell: bash
